### ISSUE TITLE
huge bug on sYEAHttlite, if it can’t fetch weather, there’s no rain

### ISSUE THREAD

**Issue by adamzaninovich** [tielur/syeahttlite#4]
huge bug on sYEAHttlite, if it can’t fetch weather, there’s no rain
huge bug on sYEAHttlite, if it can’t fetch weather, there’s no rain
huge bug on sYEAHttlite, if it can’t fetch weather, there’s no rain
huge bug on sYEAHttlite, if it can’t fetch weather, there’s no rain
huge bug on sYEAHttlite, if it can’t fetch weather, there’s no rain

**Comment by tielur** [comment]
It shouldn't be raining if the weather doesn't say it's raining
